// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resp_touch_message.proto

#ifndef PROTOBUF_resp_5ftouch_5fmessage_2eproto__INCLUDED
#define PROTOBUF_resp_5ftouch_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_resp_5ftouch_5fmessage_2eproto();
void protobuf_AssignDesc_resp_5ftouch_5fmessage_2eproto();
void protobuf_ShutdownFile_resp_5ftouch_5fmessage_2eproto();

class RespTouchMessage;

// ===================================================================

class RespTouchMessage : public ::google::protobuf::Message {
 public:
  RespTouchMessage();
  virtual ~RespTouchMessage();

  RespTouchMessage(const RespTouchMessage& from);

  inline RespTouchMessage& operator=(const RespTouchMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RespTouchMessage& default_instance();

  void Swap(RespTouchMessage* other);

  // implements Message ----------------------------------------------

  RespTouchMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RespTouchMessage& from);
  void MergeFrom(const RespTouchMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // optional string msg = 2;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 2;
  inline const ::std::string& msg() const;
  inline void set_msg(const ::std::string& value);
  inline void set_msg(const char* value);
  inline void set_msg(const char* value, size_t size);
  inline ::std::string* mutable_msg();
  inline ::std::string* release_msg();
  inline void set_allocated_msg(::std::string* msg);

  // optional int32 uv = 3;
  inline bool has_uv() const;
  inline void clear_uv();
  static const int kUvFieldNumber = 3;
  inline ::google::protobuf::int32 uv() const;
  inline void set_uv(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RespTouchMessage)
 private:
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_msg();
  inline void clear_has_msg();
  inline void set_has_uv();
  inline void clear_has_uv();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* msg_;
  ::google::protobuf::int32 code_;
  ::google::protobuf::int32 uv_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_resp_5ftouch_5fmessage_2eproto();
  friend void protobuf_AssignDesc_resp_5ftouch_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_resp_5ftouch_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static RespTouchMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// RespTouchMessage

// required int32 code = 1;
inline bool RespTouchMessage::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RespTouchMessage::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RespTouchMessage::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RespTouchMessage::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 RespTouchMessage::code() const {
  return code_;
}
inline void RespTouchMessage::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
}

// optional string msg = 2;
inline bool RespTouchMessage::has_msg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RespTouchMessage::set_has_msg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RespTouchMessage::clear_has_msg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RespTouchMessage::clear_msg() {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    msg_->clear();
  }
  clear_has_msg();
}
inline const ::std::string& RespTouchMessage::msg() const {
  return *msg_;
}
inline void RespTouchMessage::set_msg(const ::std::string& value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
}
inline void RespTouchMessage::set_msg(const char* value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
}
inline void RespTouchMessage::set_msg(const char* value, size_t size) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RespTouchMessage::mutable_msg() {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  return msg_;
}
inline ::std::string* RespTouchMessage::release_msg() {
  clear_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msg_;
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RespTouchMessage::set_allocated_msg(::std::string* msg) {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_;
  }
  if (msg) {
    set_has_msg();
    msg_ = msg;
  } else {
    clear_has_msg();
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 uv = 3;
inline bool RespTouchMessage::has_uv() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RespTouchMessage::set_has_uv() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RespTouchMessage::clear_has_uv() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RespTouchMessage::clear_uv() {
  uv_ = 0;
  clear_has_uv();
}
inline ::google::protobuf::int32 RespTouchMessage::uv() const {
  return uv_;
}
inline void RespTouchMessage::set_uv(::google::protobuf::int32 value) {
  set_has_uv();
  uv_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_resp_5ftouch_5fmessage_2eproto__INCLUDED
